global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'monitoring'
    static_configs:
      - targets: ['monitoring:5000']

  - job_name: 'service_a'
    static_configs:
      - targets: ['service_a:5000']

  - job_name: 'service_b'
    static_configs:
      - targets: ['service_b:5000']

  - job_name: 'service_c'
    static_configs:
      - targets: ['service_c:5000']

  - job_name: 'service_d'
    static_configs:
      - targets: ['service_d:5000'] 